### ISSUE TITLE
kinit_command

### ISSUE THREAD

**Issue by aroraabhinavcs** [aws-samples/aws-secrets-manager-rotation-lambdas#88]
I get this error while executing the lambda for [SecretsManagerActiveDirectoryRotationSingleUser](https://github.com/aws-samples/aws-secrets-manager-rotation-lambdas/tree/master/SecretsManagerActiveDirectoryRotationSingleUser)

Please suggest
______________________________________________

<html>
<body>

2022-08-01T16:19:08.536+05:30Copy[ERROR] ValueError: execute_kinit_command: kinit failedTraceback (most recent call last):  File "/var/task/lambda_function.py", line 136, in lambda_handler    create_secret(secrets_manager_client, arn, token, directory_name, current_dict)  File "/var/task/lambda_function.py", line 202, in create_secret    execute_kinit_command(current_dict, None, directory_name)  File "/var/task/lambda_function.py", line 446, in execute_kinit_command    raise ValueError("execute_kinit_command: kinit failed") from Exception | [ERROR] ValueError: execute_kinit_command: kinit failed Traceback (most recent call last):   File "/var/task/lambda_function.py", line 136, in lambda_handler     create_secret(secrets_manager_client, arn, token, directory_name, current_dict)   File "/var/task/lambda_function.py", line 202, in create_secret     execute_kinit_command(current_dict, None, directory_name)   File "/var/task/lambda_function.py", line 446, in execute_kinit_command     raise ValueError("execute_kinit_command: kinit failed") from Exception
-- | --

</body>
</html>

**Comment by goyalya** [comment]
@aroraabhinavcs : The lambda has to be packaged with dependencies such as kinit. Please refer to [this](https://aws.amazon.com/blogs/security/manage-your-aws-directory-service-credentials-using-aws-secrets-manager/) documentation for verifying your setup.

**Comment by aroraabhinavcs** [comment]
Thanks
